### ISSUE TITLE
[fix] 이메일 비밀번호 변경 후 메일이 전송되지 않는 이슈 

### ISSUE THREAD

**Issue by reg0145** [42organization/42gg.server.dev#518]
> ### ISSUE
> * Type: `fix`
> * Detail: fix actions from client redux
> 
> ### TODO
> 1. [x]  이메일 비밀번호 변경 후 메일이 전송되지 않는 이슈

**Comment by triplecheeseburger** [comment]
진짜 비밀번호가 틀림
